In [4]:
#A=[r + c*c for r in 1:4, c in 1:2]
#2*4 Array{Float64}:
#A'
#julia> parse.(Float64,string.(A))
using CategoricalArrays

Matrix{Float64}(undef,2,4)




2×4 Matrix{Float64}:
 1.22101e-315  1.22101e-315  1.22101e-315    2.909e-320
 5.69591e-315  1.40012e-315  9.06614e-316  NaN

In [5]:
#2 Matrixen
A = [r + c*c for r in 1:2, c in 1:2]
print(A)
B = [r + c*c for r in 1:2, c in 1:2]
print(B)
println()
#Addition
println("C:")
+(A,B)

[2 5; 3 6][2 5; 3 6]
C:


2×2 Matrix{Int64}:
 4  10
 6  12

In [6]:
#2 Matrixen
A = [r + c*c for r in 1:2, c in 1:2]
print(A)
B = [r + c*c for r in 1:2, c in 1:2]
print(B)
println()
#Multiplikation
println("C:")
*(A,B)

[2 5; 3 6][2 5; 3 6]
C:


2×2 Matrix{Int64}:
 19  40
 24  51

In [7]:
#2 Matrixen
A = [r + c*c for r in 1:2, c in 1:2]
print(A)
B = [r + c*c for r in 1:2, c in 1:2]
print(B)
println()
#Multiplikation
println("C:")
*(A,B)

[2 5; 3 6][2 5; 3 6]
C:


2×2 Matrix{Int64}:
 19  40
 24  51

In [8]:
#2 Matrixen
A = [r + c*c for r in 1:2, c in 1:2]
print(A)
B = [r + c*c for r in 1:2, c in 1:2]
print(B)
println()
#Multiplikation
println("C:")
A.*B
#Hier werden nur die Einzelnen Elemente multipliziert und nicht alle Elemente multipliziert und dann addiert

[2 5; 3 6][2 5; 3 6]
C:


2×2 Matrix{Int64}:
 4  25
 9  36

In [9]:
#2 Matrixen
A = [r + c*c for r in 1:2, c in 1:2]
print(A)
B = [r + c*c for r in 1:2, c in 1:2]
print(B)
println()
#Division 1
println("C:")
/(A,B)

[2 5; 3 6][2 5; 3 6]
C:


2×2 Matrix{Float64}:
  1.0          -1.85037e-16
 -5.32907e-16   1.0

In [10]:
#2 Matrixen
A = [r + c*c for r in 1:2, c in 1:2]
print(A)
B = [r + c*c for r in 1:2, c in 1:2]
print(B)
println()
#Division 1
println("C:")
\(A,B)
#Hier werden auch nur die einzelnen Elemente durcheinander geteilt und nicht die komplette Reihe

[2 5; 3 6][2 5; 3 6]
C:


2×2 Matrix{Float64}:
 1.0          -4.44089e-16
 1.11022e-16   1.0

In [11]:
#3*3 Matrix A
A = [r + c*c for r in 1:3, c in 1:3]
print(A)
println()
#A+1,A-1,A*2,A/2
println("C:")
A+1

[2 5 10; 3 6 11; 4 7 12]
C:


LoadError: MethodError: no method matching +(::Matrix{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at C:\Users\julia\AppData\Local\Programs\Julia-1.7.3\share\julia\base\operators.jl:655
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at C:\Users\julia\AppData\Local\Programs\Julia-1.7.3\share\julia\base\int.jl:87
  +(::LinearAlgebra.UniformScaling, ::Number) at C:\Users\julia\AppData\Local\Programs\Julia-1.7.3\share\julia\stdlib\v1.7\LinearAlgebra\src\uniformscaling.jl:145
  ...